### ISSUE TITLE
TagRanking Tutorial

### ISSUE THREAD

**Issue by leminhlong-pixta** [li-xirong/jingwei#1]
Dear TagSurvey Team, 
I have read the documents on TagSurvey, and the research is very detailed and comprehensive. While reading, I find that TagRanking seem to be very useful to what I am doing. I was wondering whether there is a tutorial on how to get data, and the data format to get the code for TagRanking running?

**Comment by li-xirong** [comment]
please see the [doit script](https://github.com/li-xirong/jingwei/blob/master/doit/do_tagranking.sh) related to TagRanking

**Comment by leminhlong-pixta** [comment]
Thank you, I think I got a bit confused `vgg-verydeep-16-fc7relu` and `vgg-verydeep-16-fc7relul2` because the key in the tagranking.py has key `vgg-verydeep-16-fc7relul2` but flickr51 and train10k only have `vgg-verydeep-16-fc7relu`

**Comment by leminhlong-pixta** [comment]
In the make_tag_rank_runs.sh file, the last line is
`python $codepath/postprocess/pickle_imagerank.py $testCollection $annotationName $simdir $resultfile  --overwrite $overwrite`
I don't think pickle_imagerank.py exists. I have tried to copy `pickle_to_imagerank.py` to the postprocess folder. However, the following error is shown:
```
[TagrankSearchEngine(flickr51,flickr51)] 0 holdout images
Traceback (most recent call last):
  File "/home/pixta-dev/dev/jingwei/util/imagesearch/sortImages.py", line 46, in <module>
    sys.exit(main())  
  File "/home/pixta-dev/dev/jingwei/util/imagesearch/sortImages.py", line 42, in main
    return process(options, args[0], args[1], args[2], args[3])
  File "/home/pixta-dev/dev/jingwei/util/imagesearch/sortImages.py", line 22, in process
    searcher = engineclass(collection, collection, engineparams, tpp=tpp, rootpath=rootpath)
  File "/home/pixta-dev/dev/jingwei/util/imagesearch/searchengine.py", line 132, in __init__
    self.rawtagnumreader = AttributeReader(collection, "rawtagnum", rootpath)
  File "/home/pixta-dev/dev/jingwei/util/imagesearch/datareader.py", line 14, in __init__
    with open(datafile) as fin:
IOError: [Errno 2] No such file or directory: '/home/pixta-dev/Documents/tag_survey_data/flickr51/MetaData/id.rawtagnum.txt'
Traceback (most recent call last):
  File "/home/pixta-dev/dev/jingwei/postprocess/pickle_imagerank.py", line 118, in <module>
    sys.exit(main())
  File "/home/pixta-dev/dev/jingwei/postprocess/pickle_imagerank.py", line 114, in main
    return process(options, args[0], args[1], args[2])
  File "/home/pixta-dev/dev/jingwei/postprocess/pickle_imagerank.py", line 23, in process
    datafiles = [x.strip() for x in open(runfile).readlines() if x.strip() and not x.strip().startswith('#')]
IOError: [Errno 2] No such file or directory: '/home/pixta-dev/Documents/tag_survey_data/flickr51/SimilarityIndex/flickr51/tagged,lemm/tagrank/train10k/vgg-verydeep-16-fc7relu,tagrank,lemm'
```


> please see the doit script related to TagRanking

**Comment by li-xirong** [comment]
hi, 

One of the error messages says "No such file or directory: '/home/pixta-dev/Documents/tag_survey_data/flickr51/MetaData/id.rawtagnum.txt'". Have you tried run the following line in the make_tag_rank_runs.sh file? It will generate the required id.rawtagnum.txt file from the tag file. 

python $codepath/util/imagesearch/countRawTagNum.py $testCollection

**Comment by leminhlong-pixta** [comment]
Yes, I noticed it a while after posting the above error. An uncommented `python $codepath/util/imagesearch/countRawTagNum.py $testCollection`. However, the following error shows:
```
Traceback (most recent call last):
  File "/home/pixta-dev/dev/jingwei/util/imagesearch/sortImages.py", line 46, in <module>
    sys.exit(main())  
  File "/home/pixta-dev/dev/jingwei/util/imagesearch/sortImages.py", line 42, in main
    return process(options, args[0], args[1], args[2], args[3])
  File "/home/pixta-dev/dev/jingwei/util/imagesearch/sortImages.py", line 24, in process
    submit([searcher], collection, annotationName, rootpath=rootpath, overwrite=overwrite)
  File "/home/pixta-dev/dev/jingwei/util/imagesearch/searchengine.py", line 153, in submit
    searchresults = searchers[j].scoreCollection(concept)
  File "/home/pixta-dev/dev/jingwei/util/imagesearch/searchengine.py", line 60, in scoreCollection
    dataset = self.readHitlist(concept)
  File "/home/pixta-dev/dev/jingwei/util/imagesearch/searchengine.py", line 89, in readHitlist
    dataset = map(str.strip, open(datafile).readlines())        
IOError: [Errno 2] No such file or directory: '/home/pixta-dev/Documents/tag_survey_data/flickr51/tagged,lemm/apple.txt'
Traceback (most recent call last):
  File "/home/pixta-dev/dev/jingwei/postprocess/pickle_imagerank.py", line 118, in <module>
    sys.exit(main())
  File "/home/pixta-dev/dev/jingwei/postprocess/pickle_imagerank.py", line 114, in main
    return process(options, args[0], args[1], args[2])
  File "/home/pixta-dev/dev/jingwei/postprocess/pickle_imagerank.py", line 23, in process
    datafiles = [x.strip() for x in open(runfile).readlines() if x.strip() and not x.strip().startswith('#')]
IOError: [Errno 2] No such file or directory: '/home/pixta-dev/Documents/tag_survey_data/flickr51/SimilarityIndex/flickr51/tagged,lemm/tagrank/train10k/vgg-verydeep-16-fc7relu,tagrank,lemm'
```
This one, I do not understand very much

**Comment by li-xirong** [comment]
Some data preparation has to be done in advance to performing the TagRanking algorithm, including knowing which images are labeled with which tag (the code assumes such information will be available at `flickr51/tagged,lemm`). Please run the following script and then re-run the rest. 

```
collection=flickr51
trainCollection=train10k
annotationName=concepts51.txt
feature=vgg-verydeep-16-fc7relu

conceptfile=$rootpath/$collection/Annotations/$annotationName

python $codepath/imagesearch/obtain_labeled_examples.py $collection $conceptfile
python $codepath/preprocess/index_features_by_tag.py $trainCollection $feature
```

Concerning the features, `vgg-verydeep-16-fc7relul2` is the L_2 normalized `vgg-verydeep-16-fc7relu`, done by the following script
```
feature=vgg-verydeep-16-fc7relu
feat_dir=$rootpath/$collection/$feature
python $codepath/util/simpleknn/norm_feat.py $feat_dir
```

**Comment by leminhlong-pixta** [comment]
Thank you very much Professor Li Xirong,

Tag Ranking seems to be training (after copying the vocab file from data folder as well). I have one more question regarding testing data. I have tried to download images from here:
_http://lixirong.net/datasets/datasets-for-image-annotation-and-retrieval_.

I understand that this file will contain all images url for all flickr test data:
_http://dl.nextcenter.org/public/nuswide/NUS-WIDE-urls.rar_

I tried to match `Photo_id` in _NUS-WIDE-urls.txt_  with images id for _flickr51_ in _.../flickr51/ImageSets/flickr51.txt_. However, it only returns about 6 matching ids. 

The purpose of my question is to visualize images for Tag Ranking in the search demo provided in the `visualize` folder. I have managed to generate a pickle file from your help.

**Comment by li-xirong** [comment]
hi, the three testsets (mirflickr, flickr51 and nus-wide) were independently constructed by distinct research teams. So there is little overlap between flickr51 and nus-wide. Given a specific photo-id, the original Flickr url (including image url) might be retrieved via a Flickr API [flickr.photo.getInfo](https://www.flickr.com/services/api/flickr.photos.getInfo.html).

**Comment by leminhlong-pixta** [comment]
Hi Professor Xirong,

Because I already have images and list of important/relevant tags and user's tags. I was wondering about the following questions:
- Are there tools available to convert text data for TagRanking? (AnnotationData, TextData) 
- How can I specify ground truths for tag ranking? I saw image  id and tags in `id.userid.lemmtags.txt`. However I am not sure whether tag order is the ground truth or not.
- How can I convert tags and images to `vgg-verydeep-16-fc7relu` features (generating feature.bin , ids.txt, minmax.txt)? 
- Is it necessary to have `feature.bin` for test data? Because normally, one would use features from training data to predict test data

**Comment by leminhlong-pixta** [comment]
Hi Professor Xirong, 

I have investigated files in `Annotation` and `TextData` I think that it is possible to create the following files using my own scripts:
`TextData/id.userid.rawtags.txt`
`TextData/id.userid.lemmtags.txt` (I assume that there is no ground truth because tag ranking is instance based )
`TextData/wn.*.txt`
`Annotations/concepts.*.txt`

I was wondering whether it would be necessary to create the following files for Tag Ranking:
`TextData/lemmtag.userfreq.imagefreq.txt`
`TextData/ucij.uuij.icij.iuij.txt`

I have noticed that the file feature.bin can be generated by following the instructions here: `jingwei/image_feature/matcovnet/`. However, I am still wondering why we need to generate `feature.bin` for MIRFLICKR or FLICKR data.

**Comment by li-xirong** [comment]
The two .txt files in TextData are not necessary for Tag Ranking. I am not sure which feature.bin you were referring to. For the Tag Ranking method, there need to be a `feature.bin` file per tag for the purpose of kernel-based density estimation, see
https://github.com/li-xirong/jingwei/blob/0a257560581f702cd394f3f28c9e0f6202827ce8/instance_based/tagranking.py#L91 
https://github.com/li-xirong/jingwei/blob/0a257560581f702cd394f3f28c9e0f6202827ce8/instance_based/tagranking.py#L50

And these feature.bin files can be generated by jingwei/preprocess/index_features_by_tag.py

**Comment by leminhlong-pixta** [comment]
Thank you for your reply,
I did not know that `feature.bin` is created for each tag of  train collection

I am wondering whether it is necessary to create feature bin for test collection like so: `tag_survey_data/flickr51/FeatureData/vgg-verydeep-16-fc7relu/feature.bin`
Currently this `feature.bin` file is read in tagranking `process` function:
https://github.com/li-xirong/jingwei/blob/0a257560581f702cd394f3f28c9e0f6202827ce8/instance_based/tagranking.py#L179
I assume the purpose of this is to get `qry_vec` (I assume this is feature of image from VGGNET) and `qry_tags` for each test item in test collection, and get tag scores:
https://github.com/li-xirong/jingwei/blob/0a257560581f702cd394f3f28c9e0f6202827ce8/instance_based/tagranking.py#L207

I am looking a way to process tag ranks of individual test images without having to generate a `feature.bin` file.

**Comment by leminhlong-pixta** [comment]
Hi Professor @li-xirong,

Going back to my previous post, I am trying to copy feature extraction method from `extract_vggnet.py`, without parallel processing in order to get image feature one by one for each item:
https://github.com/li-xirong/jingwei/blob/0a257560581f702cd394f3f28c9e0f6202827ce8/image_feature/matcovnet/extract_vggnet.m#L29-L48

I was wondering whether the following code would get everything necessary out of VGGNet to get image features similar to `extract_vgg_net.m`:
```extract_vggnet.py
import sys
import os
path = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(path, '../../'))

import numpy as np

from keras import backend as K
from keras.layers import Input, Dense
from keras.models import Model
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.applications.vgg16 import preprocess_input 
from keras.applications.vgg16 import VGG16

class VGG16FeatureExtractor(object):
	def __init__(self):
		self.net_name = "vgg-verydeep-16"
		self.image_width = 224
		self.image_height = 224
		super(VGG16FeatureExtractor, self).__init__()

	def process_image(self, image_path):
		image = load_img(image_path, target_size=(self.image_height, self.image_width))
		image_array = img_to_array(image)
		image_array = np.expand_dims(image_array, axis=0)
		image_array = preprocess_input(image_array)
		return image_array

	def init_model(self):
		self.model = VGG16(input_shape=(self.image_height, self.image_width, 3), weights="imagenet", include_top=True)
		# Remove the last two layers
		self.model.layers.pop()
		self.model.layers.pop()
		return self.model

	def get_image_vector(self, image_data):
		features = self.model.predict(image_data)
		return features
```

The VGGNet would look like this: 
![selection_005](https://user-images.githubusercontent.com/23230288/39352261-5ddbccc4-4a2e-11e8-99eb-0edeac6707a1.png)

My intention is to create `feature.bin` for each tag in training for Kernel Density Estimation similar to what you said above. Then, instead of creating a separate `feature.bin` , I would feed tag and image data to the test collection directly to the tag ranking model.

**Comment by li-xirong** [comment]
@urixiti hi Tiberio, can you please help answer  the question of @leminhlong-pixta  about the vggnet feature?

**Comment by urixiti** [comment]
Hi @leminhlong-pixta, the python code that you posted seems to be correct but the features extracted will be from first fully connected layer, instead of the second. You may easily remove the line `self.model.layers.pop()` and get similar features to the `extract_vggnet.m` script.

**Comment by leminhlong-pixta** [comment]
Hi @urixiti @li-xirong,
Thank you for your assistance, I managed to get features from vggnet for individual item now.
For the next problem, I would like to ask about the difference between `concepts*.txt` and `wn.*.txt` files. I managed to create a vocabulary file based on all tags from `TextData/id.userid.lemmtags.txt`. I assume the vocabulary file created from this is `wn.*.txt` files. However, I do not know how to generate `concepts*.txt` in that case.

**Comment by leminhlong-pixta** [comment]
Hi @urixiti @li-xirong,
 Thank you for your assistance, I managed to get features from vggnet for individual item now.
 
I have two questions regarding tag ranking data. 

1) Professor @li-xirong has told me that the following two files are not needed for TagRanking: 
`TextData/lemmtag.userfreq.imagefreq.txt`
`TextData/ucij.uuij.icij.iuij.txt`
 After looking at tag ranking code however, I found that if I want to use random walk for tag ranking, I would need these files (for FlickrContextSimilarity). I do not understand what these two files means. If it is too complicated, can I use Wu-Palmer Similarity for tag ranking instead?

2) Do we have ground truths in Tag Ranking? 
I understand we have the file: `id.userid.lemmtags.txt` for both training and testing. However, I do not understand what this file means in context of predicting top tags in tag ranking. Is it that:
- We use `id.userid.lemmtags.txt` file in training to create features for each tag in training data, this data is stored in  `FeatureIndex` folder.
- We use `id.userid.lemmtags.txt` file in testing to filter tags, used to predict confidence scores. Then we compare it with data in `Annotations/Image/concepts*.txt` directory (which I assume is ground truth labels) to see if our predictions are correct. I am still confused about this.

**Comment by li-xirong** [comment]
hi, 

In `lemmtag.userfreq.imagefreq.txt`, which was generated by [count_tags.py](https://github.com/li-xirong/jingwei/blob/master/preprocess/count_tags.py), the second column is the number of distinct users who have used a specific tag for annotate their images and the third column is the number of images that were labeled with this specific tag in a given collection, say `train10k`. See the following code:
https://github.com/li-xirong/jingwei/blob/0a257560581f702cd394f3f28c9e0f6202827ce8/util/tagsim/flickr_similarity.py#L44

As for `ucij.uuij.icij.iuij.txt`, it is about co-occurrence statistics of tag pairs, see the following code:
https://github.com/li-xirong/jingwei/blob/0a257560581f702cd394f3f28c9e0f6202827ce8/util/tagsim/flickr_similarity.py#L90

Suppose U_1 is the user set of tag t1 and V_1 is the image set of t1. Similarly, there are U_2 and V_2 for tag t2. Then, we have 
userjointfreq = | U_1 intersect U_2|,
userunionfreq  = | U_1 union U_2|,
imagejointfreq  = | V_1 intersect V_2|,
 imageunionfreq  = | V_1 union V_2|.

It is okay to use a Wu-Palmer Similarity as an alternative. 

What shall be considered as ground truth is up to your application. The file `id.userid.lemmtags.txt`  is supposed to contain user-contributed tags (or social tags) associated with each image. As user tags tend to be unreliable, they are not considered as ground truth.

**Comment by leminhlong-pixta** [comment]
@li-xirong @urixiti 
Thank you very much for your help and thorough guidance. I have managed to get TagRanking to work on my project.
I will now close the issue.
